Able to link and run CLI, seems to have issue with embedded file
$ ./openstudio.exe --help

Error: cannot load such file -- rbconfig
Backtrace:
        eval:101:in `require'
        eval:101:in `require'
        :/ruby/2.5.0/rubygems.rb:9:in `<main>'
        eval:110:in `eval'
        eval:110:in `require_embedded_absolute'
        eval:95:in `block in require'
        eval:89:in `each'
        eval:89:in `require'
        :/openstudio_cli.rb:59:in `<main>'
        eval:110:in `eval'
        eval:110:in `require_embedded_absolute'
        eval:95:in `block in require'
        eval:89:in `each'
        eval:89:in `require'
        eval:2:in `<main>'
Exception: cannot load such file -- rbconfig
ruby: unexpected return