Can't seem to be able to ignore ctor that takes tinygltf, so make it protected
The error is that std::vector's allocator isn't a friend of that class so it can't access the protected ctor...

```
In file included from /usr/include/x86_64-linux-gnu/c++/10/bits/c++allocator.h:33,
                 from /usr/include/c++/10/bits/allocator.h:46,
                 from /usr/include/c++/10/string:41,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/../utilities/core/Exception.hpp:33,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/../utilities/core/Logger.hpp:36,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfModelObjectMetaData.hpp:34,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfMetaData.hpp:34,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfForwardTranslator.hpp:34,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfForwardTranslator.cpp:30:
/usr/include/c++/10/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = openstudio::gltf::GltfUserData; _Args = {const tinygltf::Value&}; _Tp = openstudio::gltf::GltfUserData]’:
/usr/include/c++/10/bits/alloc_traits.h:512:17:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = openstudio::gltf::GltfUserData; _Args = {const tinygltf::Value&}; _Tp = openstudio::gltf::GltfUserData; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<openstudio::gltf::GltfUserData>]’
/usr/include/c++/10/bits/vector.tcc:115:30:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {const tinygltf::Value&}; _Tp = openstudio::gltf::GltfUserData; _Alloc = std::allocator<openstudio::gltf::GltfUserData>; std::vector<_Tp, _Alloc>::reference = openstudio::gltf::GltfUserData&]’
/media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfForwardTranslator.cpp:529:54:   required from here
/usr/include/c++/10/ext/new_allocator.h:150:4: error: ‘openstudio::gltf::GltfUserData::GltfUserData(const tinygltf::Value&)’ is protected within this context
  150 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfForwardTranslator.hpp:35,
                 from /media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfForwardTranslator.cpp:30:
/media/DataExt4/Software/Others/OpenStudio/src/gltf/GltfUserData.hpp:203:5: note: declared protected here
  203 |     GltfUserData(const tinygltf::Value& userDataObj);
      |     ^~~~~~~~~~~~
```