Bump conan min version to 1.28 or sqlite3 recipe will throw an error. At least it's clear here and won't puzzle people
```
ERROR: sqlite3/3.30.1: Error in package_info() method, line 116
	self.cpp_info.filenames["cmake_find_package"] = "SQLite3"
	TypeError: '_CppInfo' object does not support item assignment
```

Here's the change in the recipe: https://github.com/conan-io/conan-center-index/pull/2350/files (merged 2 hours ago)