Ignore error CS0108 which throws a ton of warning due to iddObjectType hiding inherited
````
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0108	'MasslessOpaqueMaterial.iddObjectType()' hides inherited member 'ModelObject.iddObjectType()'. Use the new keyword if hiding was intended. [D:\OpenStudio\build-vs\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	D:\OpenStudio\build-vs\csharp\generated_sources\OpenStudioModelResources\MasslessOpaqueMaterial.cs	81	
```