There's a problem with the extensibles
[18] 3_1_0(main)> sc.addSubSurface(s)
NameError: undefined local variable or method `s' for main:Object
from (pry):16:in `__pry__'
[19] 3_1_0(main)> sc.addSubSurface(ss)
[openstudio.IdfExtensibleGroup] <2> This extensible group is invalid, and so does not have an index.
RuntimeError: /home/julien/Software/Others/OpenStudio/src/utilities/idf/IdfExtensibleGroup.cpp@199 : This extensible group is invalid, and so does not have an index.
from (pry):17:in `addSubSurface'